### ISSUE TITLE
When building in Docker environment variables being ignored for redis and smx 

### ISSUE THREAD

**Issue by jmas08** [acvigue/SmartMatrixServer#35]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by acvigue** [comment]
Hi, I'm unable to reproduce this issue, what do you mean "ignored"

**Comment by jmas08** [comment]
Actually look like the Readme says MQTT_HOSTNAME code says MQTT_HOST. Works fine when I use that.  Still struggling with the older Smartmatrix-IDF code with the new server. When I updated my container I broke something.

**Comment by acvigue** [comment]
Ah, yes, I need to update the documentation. Thanks for the reminder. When you say "old smartmatrix-idf" code, what are you referring to, the newer version should be compatible with the same hardware (as long as it's an ESP32S3)

- Aiden

**Comment by jmas08** [comment]
Thanks for the response. Im running on a trinity board esp32. I had the IDF code from around Dec flashed on it. When I updated the server it broke. Look like some Dirs changed, I can no longer see the /app and /config directories in the container.

Thanks

**Comment by acvigue** [comment]
This is correct as it's now `/devices` and `/sprites`
